plugins {
    id "com.android.application"
    id "kotlin-android"
}

android {
    namespace "com.yuewu.app"
    compileSdk 34

    defaultConfig {
        applicationId "com.yuewu.app"
        minSdk 22
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile file("yuewu.keystore")
            storePassword "yuewu2024"
            keyAlias "yuewu"
            keyPassword "yuewu2024"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
